### PR TITLE
Transition to GitHub Action CI.

### PR DESCRIPTION
**Pull request by DinoBektesevic**
Change build system to tox.

TODO:
1) Add more build envs to tox
2) Build docs missing.
3) Write GH Actions config file.

### CODE REVIEW

**Comment by bsipocz** [comment]
Just a note so we don't forget: we won't need the openastronomy commit skipper action, GH announced their native one: https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

**Comment by DinoBektesevic** [comment]
As visible [here](https://github.com/DinoBektesevic/astroML/actions/runs/565114637) everything passes except flake, which will be sorted out in another PR. 

The docs-build is reserved only for ubuntu-latest because they require LaTeX to compile and setting that up can be at least a little bit complicated. I have experimented left and right to ensure Tex install would be minimal so that tests complete the fastest. As is testing with dev-astropy take the longest. 

Coverage is reserved for astropydev tests. Coverage report is just commented out because I didn't know whether they are wanted or not.

So I guess this would be the minimal working set of tasks to start from. The tests don't target what are strategically important tests for AstroML. I wasn't sure what those would be. As is, tests will run on macos, windows and ubuntu, using Python 3.7, 3.8 and 3.9 respectively, and additional test is linter and devastropy. Which I think is at least a bit odd?

I think these are actually multiple jobs really, one for docbuilding, one for lintering and a matrix for tests. One for testing with ubuntu-latest but multiple pythons (plus an astropydev job) and one that target latest python but pull all three OSs. Or is this a bit too much for AstroML and you're happy enough just running all tests in fail-fast, since they do kind of sparsely sample the same test space?

Pushed files do need a bit of a comments cleanup but no point in polishing that out, depending on answers to above.

**Comment by bsipocz** [comment]
The compatibility issues should be resolved with one exception of an astropy bug, and an issue I see locally with pymc3 that will need more time to get fixed. Among others, I've dropped support for python3.5, given it well passed its end of life.

I've also renamed master to main, so that will need adjustment in this PR.

I'll get back to the flake8 PR, and then this can be rebased and have a final review before merging.

**Comment by DinoBektesevic** [comment]
Hmm, sometimes I write a comment in my head but my hands type out something illegible. This is what the concerns in my comments were saying: 

Current tests (the tests that actually run, not tests that are leftover/commented out env definitions in tox/GA files) are, to me at least, a bit non-sensical and look something like:

| OS/Python 	| 3.7 	| 3.8  	| 3.9            	|
|-----------	        |-----	        |------	|----------------	|
| Ubuntu    	| -      	| docs 	| devastropy-cov|
| Windows   	| -    	| test 	| -              	|
| Mac-OS    	| -    	| -    	| test           	|
(I [think](https://github.com/DinoBektesevic/astroML/actions/runs/565114637))

What I was asking is if you would prefer this setup:

| OS/Python 	| 3.6  	| 3.7  	| 3.8         	| 3.9                 	|
|----------- 	|------	|------	|----------- 	|---------------------	|
| Ubuntu    	| test 	| test 	| test docs 	| test devastropy-cov |
| Windows   	| -     	| -    	| -            	| test                	|
| Mac-OS    	| -     	| -    	| -             	| test                	|
Similar to [this](https://github.com/DinoBektesevic/astroML/actions/runs/565525532) or is this a bit of an overkill

**Comment by bsipocz** [comment]
Yes, something like
| OS/Python 	| 3.6  	| 3.7  	| 3.8         	| 3.9                 	|
|----------- 	|------	|------	|----------- 	|---------------------	|
| Ubuntu    	| test & oldestdeps	| test 	| test & docs 	| test & devastropy-cov |
| Windows   	| -     	| -    	| -            	| test                	|
| Mac-OS    	| -     	| -    	| -             	| test                	|

would be great. Whether the OSX and Windows tests run on 3.9 or 3.8, it doesn't matter. In fact we said earlier that we don't suppose to support windows, but I think we are in fact compatible, so shouldn't restrict it. 
Also, at least one of the runs should be with mandatory dependencies only, the rest could be with everything installed.

**Comment by DinoBektesevic** [comment]
Ok, [all green](https://github.com/DinoBektesevic/astroML/actions/runs/602544643) except PyMC3 test fails but that must be some kind of an actual code bug. 

A PEP-8 error already crept in so that was fixed. All future tests will wait on flake to execute before running. 
Hope this is clean and easy to maintain enough for you.

**Comment by bsipocz** [comment]
Thank you @DinoBektesevic! PyMC3 is annoying, and I'll fix it separately.

**Pull request merged**
