### PR TITLE
Pull request #103 with fixes

### PR DESCRIPTION
**Pull request by Engineero**
This pull request merges #103 with fixes for the issues that were preventing it from passing Travis CI builds. Or at least it should. It passes all tests on my machine. I also submitted this as a pull request to their repo, so if they get around to accepting it, the changes may show up in their original pull request.

### CODE REVIEW

**Comment by Engineero** [comment]
Sure enough, all tests passed!

Next stop, address some of these other deprecation warnings.

**Comment by Engineero** [comment]
Added fixes to some deprecation warnings as well. Passed tests on my machine, now waiting for Travis.

**Comment by Engineero** [comment]
One thing I am not certain of: I am getting a PDF integral that is twice as large as it should be when using `GaussianMixture` instead of `GMM`. I have the test passing right now, but it might bear looking into a bit more.

**Comment by bsipocz** [comment]
This change is incompatible with <0.18 scikit-learn versions, meaning the decision in #114 is a blocker for this PR.

**Comment by Engineero** [comment]
@bsipocz sorry, I don't see the actual decision in #114, just your initial comment opening the issue and then references to it in some other issues. If no decision is made to support sklearn older than 0.18, then 114 does not block this.

**Comment by bsipocz** [comment]
@Engineero - I'll get back to this soon.

**Comment by bsipocz** [comment]
#125 supersedes this one.

Thank you @Engineero. Some of the contributions from here were included in other PRs that got cherry-picked into #125.

Thank you @Engineero!

**Pull request closed without merging**
