### PR TITLE
MNT: Ignore import error in pytest collection

### PR DESCRIPTION
**Pull request by pllim**
This is an automated update made by the `batchpr` tool :robot: to future-proof test collection behavior `pytest-doctestplus` - feel free to close if it doesn't look good or isn't relevant! You can report issues to @pllim.

### CODE REVIEW

**Comment by bsipocz** [comment]
I like to think we don't need this here. On the other hand the failures are real, and I see them on master, too. 

I'll  investigate and fix it as I can't recall running into the same pytest failure elsewhere (but then astroml is not using the astropy test runner machinery)

**Comment by pllim** [comment]
No worries. It was automated PR. Feel free to close if you don't need it.

**Comment by bsipocz** [comment]
Thanks @pllim! I probably will close it, but will first investigate for the master breakage (I guess it will boil down to a doctestplus issue).

**Comment by pllim** [comment]
Yeah, looks like the job picked up ` doctestplus-0.5.0` for some reason even though you released 0.6.

**Comment by bsipocz** [comment]
@pllim - Thanks for the PR! However, as this has been fixed upstream,  I'm closing this now without merging.

**Pull request closed without merging**
