### PR TITLE
in sklearn 0.14+ Setting compute_importances=True is no longer required in sklearn.tree.DecisionTreeClassifier

### PR DESCRIPTION
**Pull request by richardgmcmahon**
in sklearn 0.14+ Setting compute_importances=True is no longer required in sklearn.tree.DecisionTreeClassifier

I am a newbie to forking and pulling but fig_rrlyrae_treevis.py was crashing with the error:

sklearn.**version**:  0.16.1
astroML.**version**:  0.3

 File "fig_rrlyrae_treevis.py", line 242, in <module>
    random_state=0, criterion='entropy')
TypeError: **init**() got an unexpected keyword argument 'compute_importances'

### CODE REVIEW

**Comment by jakevdp** [comment]
Thanks for catching this! I'd like to merge this, but hopefully you can first address a couple things:

- the commit contains two files in addition to the main changes. Could you remove those?
- the new code does not use PEP-8 recommended four spaces for indentation.

Other than that, this is good to be merged.

**Comment by jakevdp** [comment]
One more thing: a raw ``except`` is not a desirable thing! Can you change it to ``except ValueError`` or ``except TypeError`` (whichever is appropriate)? Thanks.

**Comment by richardgmcmahon** [comment]
OK, will fix the PEP, etc. I’ll need to see if I can git rm or will refork

**Comment by jakevdp** [comment]
It's fine to ``git rm`` on this branch and then add a new commit.

**Comment by bsipocz** [comment]
The figures has been moved out of this repo, I'll see whether this PR is still relevant for the new repo and if yes will move the content there.

**Pull request closed without merging**
